version: "3.7"
services:
  
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data/db-files/
    ports: 
     - 5432:5432
    # expose:
    #   - 5432
    
    volumes:
       - postgres_volume:/var/lib/postgresql/data/db-files/
      
  mongo:
    image: mongo
    restart: always
    ports:
        - 27017:27017
    # expose:
    #   - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
       - mongodb_volume:/data/db
        
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
  
  nginx:
   build: ./nginx
   container_name: nginx
   restart: always
   #PORTS defines ports reachable from the outside world, like a browser or other clients
   ports: 
     - "82:80"
     - "443:443"
     - "8082:8080"

  backend:
   build: ./backend
   restart: always
   expose: 
     - 8080
   

  frontend:
   build: ./frontend/cooking-site-v2
   restart: always
   expose: 
     - 8080 
   ports: 
    - 83:8080
volumes:
   postgres_volume:
   mongodb_volume:
  #backend:
  #  build: ./backend
  #  restart: always
  #  ports: 8080:8080
