version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data/db-files/
    ports: 
      - 5432:5432
    volumes:
        - postgres_volume:/var/lib/postgresql/data/db-files/
      
  mongo:
    image: mongo
    restart: always
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
        - mongodb_volume:/data/db
        
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      
volumes:
    postgres_volume:
    mongodb_volume:
  #backend:
  #  build: ./backend
  #  restart: always
  #  ports: 8080:8080
